apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-capstone-flask-app
  region: us-west-2

iam:
  withOIDC: true

nodeGroups:
  - name: capstone-project-flask-app
    instanceType: t2.small
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: west2
