apiVersion: apps/v1
kind: Deployment

metadata:
  name: capstone-flask-app-${LABEL_VERSION}

spec:
  # Number of replicas (pods) that should be running.
  replicas: 1
  
  selector:
    matchLabels:
      app: capstone-flask-app
      version: ${LABEL_VERSION}

  # Template to create new pod
  template:
    metadata:
      labels:
        app: capstone-flask-app
        version: ${LABEL_VERSION}

    spec:
      containers:
        - name: capstone-flask-app
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 80
