# Specify the API version and kind for the Kubernetes Deployment resource
apiVersion: apps/v1
kind: Deployment

# Metadata section for the Deployment resource
metadata:
  # The name of the Deployment resource, using a dynamic label version
  name: udacity-capstone-project-${LABEL_VERSION}

# Specification section for the Deployment resource
spec:
  # Number of replicas (pods) that should be running at any given time
  replicas: 1

  # Selector to determine which pods this Deployment should manage
  selector:
    matchLabels:
      app: udacity-capstone-project
      version: ${LABEL_VERSION}

  # Pod template used by the Deployment to create new pods
  template:
    # Metadata for the pod template
    metadata:
      # Labels to be applied to the pods created from this template
      labels:
        app: udacity-capstone-project
        version: ${LABEL_VERSION}

    # Specification for the pod template
    spec:
      # Containers that should be part of the pod
      containers:
        # Container name
        - name: udacity-capstone-project
          # Docker image to use for the container, using a dynamic Docker image tag
          image: ${DOCKER_IMAGE}
          # Ports to expose in the container
          ports:
            - containerPort: 80
