apiVersion: v1
kind: Service
metadata:
  name: capstone-flask-app-green
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: capstone-flask-app
    version: ${LABEL_VERSION}
  type: LoadBalancer