apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-flask-app-1-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-flask-app
      version: 1-0
  template:
    metadata:
      labels:
        app: capstone-flask-app
        version: 1-0
    spec:
      containers:
        - name: capstone-flask-app
          image: luthevy2001/capstone-flask-app:1.0
          ports:
            - containerPort: 80
